spring:
  profiles:
    active: dev
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:25432/avengers
    username: dio.avenger
    password: dio.avenger
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
      baselineOnMigrate: true

